[book]
authors = ["yhwu-is"]
language = "zh"
multilingual = false
src = "src"
title = "计算机系统——从小白学起"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = true
copy-fonts = true
additional-css = ["theme/custom.css"]
no-section-label = true
site-url = "/Computer-System-Start-From-a-Newbie/"
git-repository-url = "https://github.com/yhwu-is/Computer-System-Start-From-a-Newbie"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/yhwu-is/Computer-System-Start-From-a-Newbie/edit/master/{path}"
input-404 = "404.md"

[output.html.fold]
enable = true
level = 1